### ISSUE TITLE
executeWithCursorPagination have notify me that it expect 0 argument but in declare file it have some

### ISSUE THREAD

**Issue by tin-pham** [charlie-hadden/kysely-paginate#19] opened 2023-11-11 00:24 UTC
![image](https://github.com/charlie-hadden/kysely-paginate/assets/20679090/24c2c0db-b2a5-45ba-8aeb-1fcb6f732e5a)
![image](https://github.com/charlie-hadden/kysely-paginate/assets/20679090/66d0c585-adc1-48f9-b278-16985aefbc1f)
![image](https://github.com/charlie-hadden/kysely-paginate/assets/20679090/5c8c614d-a8bc-4caf-bb2d-9991b47faccb)

My tsconfig.json

```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Node 18 + ESM + Strictest",
  "compilerOptions": {
    "module": "CommonJS",
    "moduleResolution": "Node",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES6",
    "inlineSourceMap": true,
    "inlineSources": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "resolveJsonModule": true,
    "allowUnusedLabels": false,
    "allowUnreachableCode": false,
    "exactOptionalPropertyTypes": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true
  },
  "include": [
    "./src/**/*",
    "./config/**/*",
    "./jest.config.ts",
    "./tsconfig.json",
    "./.eslintrc"
  ],
  "exclude": ["node_modules", "dist"]
}

```

**Comment by charlie-hadden** [comment] 2023-12-27 13:05
I'm going to go ahead and close this as I haven't been able to reproduce it. It's possible that it was also caused by some issues with how the ESM types were packaged which I have since resolved.

**Closed by charlie-hadden** 2023-12-27 13:05 UTC
